"""Pack the Blender hero renders into the game's sprite sheets.

    python tools/hero_pack.py <render_dir> <out_dir> [<rust_out>]

<render_dir>/plain/<row>_<col>.png (and optionally coat/...) come from
tools/blender/hero_sheet.py at 4x cell size. Each frame is downscaled to a
96x88 cell, snapped to one palette shared by every frame (so colours never
flicker between frames), given a 1 px dark outline so he reads against snow,
and mirrored so he faces right. Writes hero.png (and hero_coat.png when the
coat renders exist) as a 5-column grid, plus a 3x preview. With <rust_out> it
also writes the row indices and, per cell, where his hands and hips are
(src/hero_frames.rs), so the game can put his hands on a ledge or tie the rope
to his harness.
"""
import json
import os
import sys
from PIL import Image

CELL = (96, 88)
COLS = 5
COLOURS = 28
OUTLINE = (18, 20, 28, 255)
ALPHA_CUT = 110


def rows_in(d):
    return 1 + max(int(f.split("_")[0]) for f in os.listdir(d) if f.endswith(".png"))


def load_cells(d):
    cells = {}
    for r in range(rows_in(d)):
        for c in range(COLS):
            p = os.path.join(d, f"{r}_{c}.png")
            if not os.path.exists(p):
                continue
            im = Image.open(p).convert("RGBA").resize(CELL, Image.LANCZOS)
            a = im.getchannel("A").point(lambda v: 255 if v > ALPHA_CUT else 0)
            im.putalpha(a)
            cells[(r, c)] = im.transpose(Image.FLIP_LEFT_RIGHT)
    return cells


def rare(p):
    # small but important colours (rope blue, coat yellow, steel, orange accents) that a plain
    # median cut would merge into the big red/black areas
    r, g, b = p
    return b > r + 20 or (r > 120 and g > 90 and b < 70 and g > r * 0.6) or (min(p) > 110 and max(p) - min(p) < 35)


def cut(px, n):
    strip = Image.new("RGB", (len(px), 1))
    strip.putdata(px)
    q = strip.quantize(colors=n, method=Image.Quantize.MEDIANCUT, dither=Image.Dither.NONE)
    return q.getpalette()[: 3 * len(set(q.get_flattened_data()))]


def palette_from(all_cells):
    # every opaque pixel from every frame -> one shared palette, plus a few slots for rare colours
    px = []
    for im in all_cells:
        px += [p[:3] for p in im.get_flattened_data() if p[3]]
    few = [p for p in px if rare(p)]
    colours = cut(px, COLOURS - 8) + (cut(few, 8) if few else [])
    pal = Image.new("P", (1, 1))
    pal.putpalette(colours + colours[:3] * (256 - len(colours) // 3))
    return pal


def snap(im, pal):
    rgb = im.convert("RGB").quantize(palette=pal, dither=Image.Dither.NONE).convert("RGB")
    out = rgb.convert("RGBA")
    out.putalpha(im.getchannel("A"))
    return out


def outline(im):
    w, h = im.size
    src = im.load()
    out = im.copy()
    dst = out.load()
    for y in range(h):
        for x in range(w):
            if src[x, y][3]:
                continue
            for dx, dy in ((1, 0), (-1, 0), (0, 1), (0, -1)):
                nx, ny = x + dx, y + dy
                if 0 <= nx < w and 0 <= ny < h and src[nx, ny][3]:
                    dst[x, y] = OUTLINE
                    break
    return out


def sheet(cells, pal):
    rows = 1 + max(r for r, _ in cells)
    out = Image.new("RGBA", (CELL[0] * COLS, CELL[1] * rows), (0, 0, 0, 0))
    for (r, c), im in cells.items():
        out.paste(outline(snap(im, pal)), (c * CELL[0], r * CELL[1]))
    return out


def preview(sh, path):
    bg = Image.new("RGBA", sh.size, (205, 214, 226, 255))
    bg.alpha_composite(sh)
    bg.resize((sh.width * 3, sh.height * 3), Image.NEAREST).save(path)


def rust(meta, path):
    rows = 1 + max(int(k.split("_")[0]) for k in meta)
    names = [meta[f"{r}_0"]["row"] for r in range(rows)]

    def table(key):
        out = []
        for r in range(rows):
            cells = []
            for c in range(COLS):
                x, y = meta[f"{r}_{c}"][key]
                # sprite-local pixels from the bottom-centre anchor, y up
                cells.append(f"({x - CELL[0] / 2:.1f}, {CELL[1] - y:.1f})")
            out.append(f"    [{', '.join(cells)}], // {names[r]}")
        return "\n".join(out)

    lines = ["// Generated by tools/hero_pack.py from the Blender renders. Do not edit by hand.", "",
             f"pub const ROWS: u32 = {rows};"]
    lines += [f"pub const {n.upper()}: usize = {r};" for r, n in enumerate(names)]
    lines += ["", "/// Midpoint of his hands in each cell, sprite pixels from the bottom-centre anchor (y up, facing right).",
              f"pub const HANDS: [[(f32, f32); {COLS}]; {rows}] = [", table("hands"), "];", "",
              "/// His hips (where the harness and rope tie in), same space.",
              f"pub const HIPS: [[(f32, f32); {COLS}]; {rows}] = [", table("hips"), "];", ""]
    open(path, "w", newline="\n").write("\n".join(lines))
    print(path, rows, "rows")


def main():
    src, dst = sys.argv[1], sys.argv[2]
    os.makedirs(dst, exist_ok=True)
    sets = {name: load_cells(os.path.join(src, name)) for name in ("plain", "coat")
            if os.path.isdir(os.path.join(src, name))}
    pal = palette_from([im for cells in sets.values() for im in cells.values()])
    for name, cells in sets.items():
        sh = sheet(cells, pal)
        fn = "hero.png" if name == "plain" else "hero_coat.png"
        sh.save(os.path.join(dst, fn))
        preview(sh, os.path.join(dst, fn.replace(".png", "_preview.png")))
        print(fn, len(cells), "cells")
    if len(sys.argv) > 3:
        rust(json.load(open(os.path.join(src, "meta.json"))), sys.argv[3])


if __name__ == "__main__":
    main()
